### PR TITLE
feat: add trending up and down icons

### PR DESCRIPTION
**Pull request by killian-dv**
## I have read the [CONTRIBUTING.md](https://github.com/pqoqubbw/icons/blob/main/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Add icons

## What is the new behavior?

Trending-up and trending-down icons

https://github.com/user-attachments/assets/79146b0f-fdef-4db3-912b-eb8d72b45f25

Please attach a short video demo of the changes.

### CODE REVIEW

**Comment by killian-dv** [comment]
I see that some people define their Variants animation in a constant and others write them directly as props in the path. Which do you prefer? Perhaps the second solution, which makes it easy to copy and paste just the animated svg without the container and put it in our own components?

**Comment by pqoqubbw** [comment]
> I see that some people define their Variants animation in a constant and others write them directly as props in the path. Which do you prefer? Perhaps the second solution, which makes it easy to copy and paste just the animated svg without the container and put it in our own components?

It depends on the amount of data. if it's a few lines, I prefer to write them inline, but as in your case, if you have many configurations for the animation, it's better to define them as const and pass them in a tag

**Comment by pqoqubbw** [comment]
about the animation, it's beautiful, thanks! but could you add some bounce at the end? when the arrow is showing, i think it would improve the feel of it

it could be the bounce like we have for `logout` but in the opposite direction

**Comment by killian-dv** [comment]
I don't know exactly what you wanted. I made 2 different commits with 2 versions of bounce. Choose the one you prefer 🚀

**Comment by killian-dv** [comment]
> > I see that some people define their Variants animation in a constant and others write them directly as props in the path. Which do you prefer? Perhaps the second solution, which makes it easy to copy and paste just the animated svg without the container and put it in our own components?
> 
> It depends on the amount of data. if it's a few lines, I prefer to write them inline, but as in your case, if you have many configurations for the animation, it's better to define them as const and pass them in a tag

Thanks for your opinion, I've corrected the code accordingly.

**Pull request merged**
