### PR TITLE
wifi icon animation

### PR DESCRIPTION
**Pull request by tyrellshawn**
## I have read the [CONTRIBUTING.md](https://github.com/pqoqubbw/icons/blob/main/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?
feature

## Demo

https://github.com/user-attachments/assets/b10f72f6-a34f-4e6c-89d5-b694351e68db

Please attach a short video demo of the changes.

### CODE REVIEW

**Comment by pqoqubbw** [comment]
could you please show full icon on default state and hide + start an animation when hovering? as we do for other icons, cause now it would be strange to see just a dot

**Comment by pqoqubbw** [comment]
and you didn't run `yarn lint` i guess 👀

**Comment by tyrellshawn** [comment]
Updated please review @pqoqubbw 

https://github.com/user-attachments/assets/2248ef31-3af6-4d63-991d-4fb2cb19eac3

**Comment by pqoqubbw** [comment]
> Updated please review @pqoqubbw
> 
>  Screen.Recording.2024-11-10.183147.mp4

awesome, thanks!

**Pull request merged**
